export interface CuratedArtist {
  name: string;
  genre: string;
  priority?: boolean;
}

export const CURATED_ENGLISH_ARTISTS: CuratedArtist[] = [
  // ==========================================
  // TOP PRIORITY FULL DISCOGRAPHY ACTS
  // ==========================================
  { name: 'Frank Ocean', genre: 'r-and-b', priority: true },
  { name: 'Kanye West', genre: 'hip-hop', priority: true },
  { name: 'A$AP Rocky', genre: 'hip-hop', priority: true },
  { name: 'Travis Scott', genre: 'hip-hop', priority: true },
  { name: 'Playboi Carti', genre: 'hip-hop', priority: true },
  { name: 'Kendrick Lamar', genre: 'hip-hop', priority: true },
  { name: 'Drake', genre: 'hip-hop', priority: true },
  { name: 'Tyler, The Creator', genre: 'hip-hop', priority: true },
  { name: 'The Weeknd', genre: 'pop', priority: true },
  { name: 'Taylor Swift', genre: 'pop', priority: true },
  { name: 'Mac Miller', genre: 'hip-hop', priority: true },
  { name: 'Juice WRLD', genre: 'hip-hop', priority: true },

  // ==========================================
  // 1. POP
  // ==========================================
  { name: 'Ed Sheeran', genre: 'pop', priority: true },
  { name: 'Dua Lipa', genre: 'pop', priority: true },
  { name: 'Ariana Grande', genre: 'pop', priority: true },
  { name: 'Bruno Mars', genre: 'pop', priority: true },
  { name: 'Billie Eilish', genre: 'pop', priority: true },
  { name: 'Justin Bieber', genre: 'pop' },
  { name: 'Harry Styles', genre: 'pop' },
  { name: 'Miley Cyrus', genre: 'pop' },
  { name: 'Adele', genre: 'pop' },
  { name: 'Katy Perry', genre: 'pop' },
  { name: 'Lady Gaga', genre: 'pop' },
  { name: 'Shawn Mendes', genre: 'pop' },
  { name: 'Olivia Rodrigo', genre: 'pop' },
  { name: 'Chappell Roan', genre: 'pop' },
  { name: 'Sabrina Carpenter', genre: 'pop' },
  { name: 'Charli xcx', genre: 'pop' },
  { name: 'Lorde', genre: 'pop' },
  { name: 'Sia', genre: 'pop' },
  { name: 'Sam Smith', genre: 'pop' },
  { name: 'Camila Cabello', genre: 'pop' },
  { name: 'Halsey', genre: 'pop' },
  { name: 'Charlie Puth', genre: 'pop' },
  { name: 'Zayn', genre: 'pop' },
  { name: 'Lizzo', genre: 'pop' },
  { name: 'Meghan Trainor', genre: 'pop' },
  { name: 'Ellie Goulding', genre: 'pop' },
  { name: 'Bebe Rexha', genre: 'pop' },
  { name: 'Kelly Clarkson', genre: 'pop' },
  { name: 'Pink', genre: 'pop' },
  { name: 'Britney Spears', genre: 'pop' },
  { name: 'Christina Aguilera', genre: 'pop' },
  { name: 'Justin Timberlake', genre: 'pop' },
  { name: 'Madonna', genre: 'pop' },
  { name: 'Michael Jackson', genre: 'pop' },
  { name: 'George Michael', genre: 'pop' },
  { name: 'Phil Collins', genre: 'pop' },
  { name: 'Elton John', genre: 'pop' },
  { name: 'Celine Dion', genre: 'pop' },
  { name: 'Whitney Houston', genre: 'pop' },
  { name: 'Mariah Carey', genre: 'pop' },
  { name: 'Janet Jackson', genre: 'pop' },
  { name: 'Kylie Minogue', genre: 'pop' },
  { name: 'Robbie Williams', genre: 'pop' },
  { name: 'Tate McRae', genre: 'pop' },
  { name: 'Conan Gray', genre: 'pop' },
  { name: 'Troye Sivan', genre: 'pop' },
  { name: 'Reneé Rapp', genre: 'pop' },
  { name: 'Benson Boone', genre: 'pop' },
  { name: 'Teddy Swims', genre: 'pop' },

  // ==========================================
  // 2. ROCK
  // ==========================================
  { name: 'Queen', genre: 'rock', priority: true },
  { name: 'Nirvana', genre: 'rock', priority: true },
  { name: "Guns N' Roses", genre: 'rock', priority: true },
  { name: 'Led Zeppelin', genre: 'rock', priority: true },
  { name: 'AC/DC', genre: 'rock', priority: true },
  { name: 'The Killers', genre: 'rock' },
  { name: 'Foo Fighters', genre: 'rock' },
  { name: 'Red Hot Chili Peppers', genre: 'rock' },
  { name: 'Green Day', genre: 'rock' },
  { name: 'Linkin Park', genre: 'rock' },
  { name: 'Coldplay', genre: 'rock' },
  { name: 'Muse', genre: 'rock' },
  { name: 'Imagine Dragons', genre: 'rock' },
  { name: 'Arctic Monkeys', genre: 'rock' },
  { name: 'The Rolling Stones', genre: 'rock' },
  { name: 'The Beatles', genre: 'rock' },
  { name: 'Pink Floyd', genre: 'rock' },
  { name: 'The Who', genre: 'rock' },
  { name: 'The Doors', genre: 'rock' },
  { name: 'Aerosmith', genre: 'rock' },
  { name: 'Bon Jovi', genre: 'rock' },
  { name: 'U2', genre: 'rock' },
  { name: 'Oasis', genre: 'rock' },
  { name: 'Radiohead', genre: 'rock' },
  { name: 'R.E.M.', genre: 'rock' },
  { name: 'Pearl Jam', genre: 'rock' },
  { name: 'Soundgarden', genre: 'rock' },
  { name: 'Alice in Chains', genre: 'rock' },
  { name: 'The Smashing Pumpkins', genre: 'rock' },
  { name: 'Weezer', genre: 'rock' },
  { name: 'Blink-182', genre: 'rock' },
  { name: 'Fall Out Boy', genre: 'rock' },
  { name: 'My Chemical Romance', genre: 'rock' },
  { name: 'Paramore', genre: 'rock' },
  { name: 'Panic! At The Disco', genre: 'rock' },
  { name: 'Twenty One Pilots', genre: 'rock' },
  { name: 'Kings of Leon', genre: 'rock' },
  { name: 'The Black Keys', genre: 'rock' },
  { name: 'Cage The Elephant', genre: 'rock' },
  { name: 'Royal Blood', genre: 'rock' },
  { name: 'Nothing But Thieves', genre: 'rock' },
  { name: 'Sam Fender', genre: 'rock' },
  { name: 'Greta Van Fleet', genre: 'rock' },
  { name: 'Maneskin', genre: 'rock' },

  // ==========================================
  // 3. ALTERNATIVE & INDIE
  // ==========================================
  { name: 'The Strokes', genre: 'indie', priority: true },
  { name: 'Phoebe Bridgers', genre: 'indie', priority: true },
  { name: 'The Lumineers', genre: 'indie' },
  { name: 'Bon Iver', genre: 'indie' },
  { name: 'Vance Joy', genre: 'indie' },
  { name: 'George Ezra', genre: 'indie' },
  { name: 'Of Monsters and Men', genre: 'indie' },
  { name: 'Mumford & Sons', genre: 'indie' },
  { name: 'Hozier', genre: 'indie' },
  { name: 'Florence and the Machine', genre: 'indie' },
  { name: 'Foster the People', genre: 'indie' },
  { name: 'MGMT', genre: 'indie' },
  { name: 'Fleet Foxes', genre: 'indie' },
  { name: 'Vampire Weekend', genre: 'indie' },
  { name: 'Arcade Fire', genre: 'indie' },
  { name: 'The National', genre: 'indie' },
  { name: 'Two Door Cinema Club', genre: 'indie' },
  { name: 'The 1975', genre: 'indie' },
  { name: 'Glass Animals', genre: 'indie' },
  { name: 'Foals', genre: 'indie' },
  { name: 'Wallows', genre: 'indie' },
  { name: 'Boygenius', genre: 'indie' },
  { name: 'Clairo', genre: 'indie' },
  { name: 'Beabadoobee', genre: 'indie' },
  { name: 'Mac DeMarco', genre: 'indie' },
  { name: 'Mitski', genre: 'indie' },
  { name: 'Japanese Breakfast', genre: 'indie' },
  { name: 'Snail Mail', genre: 'indie' },
  { name: 'Soccer Mommy', genre: 'indie' },
  { name: 'Alvvays', genre: 'indie' },
  { name: 'Beach House', genre: 'indie' },
  { name: 'Tame Impala', genre: 'indie' },
  { name: 'Unknown Mortal Orchestra', genre: 'indie' },
  { name: 'Men I Trust', genre: 'indie' },
  { name: 'Cigarettes After Sex', genre: 'indie' },
  { name: 'The War on Drugs', genre: 'indie' },
  { name: 'Big Thief', genre: 'indie' },
  { name: 'Father John Misty', genre: 'indie' },
  { name: 'Sufjan Stevens', genre: 'indie' },
  { name: 'Iron & Wine', genre: 'indie' },
  { name: 'Death Cab for Cutie', genre: 'indie' },
  { name: 'The Postal Service', genre: 'indie' },
  { name: 'Modest Mouse', genre: 'indie' },
  { name: 'Bright Eyes', genre: 'indie' },
  { name: 'The Shins', genre: 'indie' },
  { name: 'Franz Ferdinand', genre: 'indie' },
  { name: 'Interpol', genre: 'indie' },
  { name: 'Yeah Yeah Yeahs', genre: 'indie' },
  { name: 'Phoenix', genre: 'indie' },
  { name: 'Grizzly Bear', genre: 'indie' },

  // ==========================================
  // 4. HIP-HOP & RAP
  // ==========================================
  { name: 'Kendrick Lamar', genre: 'hip-hop', priority: true },
  { name: 'Drake', genre: 'hip-hop', priority: true },
  { name: 'Travis Scott', genre: 'hip-hop', priority: true },
  { name: 'Eminem', genre: 'hip-hop', priority: true },
  { name: 'Post Malone', genre: 'hip-hop' },
  { name: 'J. Cole', genre: 'hip-hop' },
  { name: 'A$AP Rocky', genre: 'hip-hop' },
  { name: 'Playboi Carti', genre: 'hip-hop' },
  { name: 'Lil Uzi Vert', genre: 'hip-hop' },
  { name: 'Future', genre: 'hip-hop' },
  { name: 'Young Thug', genre: 'hip-hop' },
  { name: '50 Cent', genre: 'hip-hop' },
  { name: 'Kanye West', genre: 'hip-hop' },
  { name: 'Lil Wayne', genre: 'hip-hop' },
  { name: 'Nas', genre: 'hip-hop' },
  { name: 'Jay-Z', genre: 'hip-hop' },
  { name: 'The Notorious B.I.G.', genre: 'hip-hop' },
  { name: '2Pac', genre: 'hip-hop' },
  { name: 'Snoop Dogg', genre: 'hip-hop' },
  { name: 'Dr. Dre', genre: 'hip-hop' },
  { name: 'Ice Cube', genre: 'hip-hop' },
  { name: 'Outkast', genre: 'hip-hop' },
  { name: 'A Tribe Called Quest', genre: 'hip-hop' },
  { name: 'Wu-Tang Clan', genre: 'hip-hop' },
  { name: 'Mac Miller', genre: 'hip-hop' },
  { name: 'Juice WRLD', genre: 'hip-hop' },
  { name: 'XXXTentacion', genre: 'hip-hop' },
  { name: '21 Savage', genre: 'hip-hop' },
  { name: 'Metro Boomin', genre: 'hip-hop' },
  { name: 'Gunna', genre: 'hip-hop' },
  { name: 'Lil Baby', genre: 'hip-hop' },
  { name: 'Roddy Ricch', genre: 'hip-hop' },
  { name: 'Jack Harlow', genre: 'hip-hop' },
  { name: 'Tyler, The Creator', genre: 'hip-hop' },
  { name: 'Earl Sweatshirt', genre: 'hip-hop' },
  { name: 'Denzel Curry', genre: 'hip-hop' },
  { name: 'JID', genre: 'hip-hop' },
  { name: 'Joey Bada$$', genre: 'hip-hop' },
  { name: 'Pusha T', genre: 'hip-hop' },
  { name: 'Schoolboy Q', genre: 'hip-hop' },
  { name: 'Vince Staples', genre: 'hip-hop' },
  { name: 'Danny Brown', genre: 'hip-hop' },
  { name: 'Freddie Gibbs', genre: 'hip-hop' },
  { name: 'Run The Jewels', genre: 'hip-hop' },
  { name: 'Cordae', genre: 'hip-hop' },
  { name: 'Central Cee', genre: 'hip-hop' },
  { name: 'Dave', genre: 'hip-hop' },
  { name: 'Stormzy', genre: 'hip-hop' },
  { name: 'Skepta', genre: 'hip-hop' },
  { name: 'Little Simz', genre: 'hip-hop' },

  // ==========================================
  // 5. R&B & SOUL
  // ==========================================
  { name: 'Frank Ocean', genre: 'r-and-b', priority: true },
  { name: 'SZA', genre: 'r-and-b', priority: true },
  { name: 'Daniel Caesar', genre: 'r-and-b', priority: true },
  { name: 'Miguel', genre: 'r-and-b' },
  { name: 'Khalid', genre: 'r-and-b' },
  { name: 'Chris Brown', genre: 'r-and-b' },
  { name: 'Usher', genre: 'r-and-b' },
  { name: 'Alicia Keys', genre: 'r-and-b' },
  { name: 'John Legend', genre: 'r-and-b' },
  { name: 'Beyoncé', genre: 'r-and-b' },
  { name: 'H.E.R.', genre: 'r-and-b' },
  { name: 'Jhené Aiko', genre: 'r-and-b' },
  { name: 'Solange', genre: 'r-and-b' },
  { name: 'Ne-Yo', genre: 'r-and-b' },
  { name: 'Bryson Tiller', genre: 'r-and-b' },
  { name: 'Kehlani', genre: 'r-and-b' },
  { name: 'Summer Walker', genre: 'r-and-b' },
  { name: 'Brent Faiyaz', genre: 'r-and-b' },
  { name: 'Giveon', genre: 'r-and-b' },
  { name: 'Steve Lacy', genre: 'r-and-b' },
  { name: 'Leon Bridges', genre: 'r-and-b' },
  { name: 'Anderson .Paak', genre: 'r-and-b' },
  { name: 'Silk Sonic', genre: 'r-and-b' },
  { name: 'Stevie Wonder', genre: 'r-and-b' },
  { name: 'Marvin Gaye', genre: 'r-and-b' },
  { name: 'Aretha Franklin', genre: 'r-and-b' },
  { name: 'Otis Redding', genre: 'r-and-b' },
  { name: 'Sam Cooke', genre: 'r-and-b' },
  { name: 'Al Green', genre: 'r-and-b' },
  { name: 'Etta James', genre: 'r-and-b' },
  { name: 'Bill Withers', genre: 'r-and-b' },
  { name: 'D\'Angelo', genre: 'r-and-b' },
  { name: 'Erykah Badu', genre: 'r-and-b' },
  { name: 'Lauryn Hill', genre: 'r-and-b' },
  { name: 'Maxwell', genre: 'r-and-b' },
  { name: 'Sade', genre: 'r-and-b' },
  { name: 'Toni Braxton', genre: 'r-and-b' },
  { name: 'TLC', genre: 'r-and-b' },
  { name: 'Destiny\'s Child', genre: 'r-and-b' },
  { name: 'Boyz II Men', genre: 'r-and-b' },
  { name: 'Teyana Taylor', genre: 'r-and-b' },
  { name: 'Snoh Aalegra', genre: 'r-and-b' },
  { name: 'Victoria Monét', genre: 'r-and-b' },
  { name: 'Jorja Smith', genre: 'r-and-b' },
  { name: 'Mahalia', genre: 'r-and-b' },
  { name: 'Cleo Sol', genre: 'r-and-b' },
  { name: 'SAULT', genre: 'r-and-b' },

  // ==========================================
  // 6. EDM & ELECTRONIC
  // ==========================================
  { name: 'Daft Punk', genre: 'electronic', priority: true },
  { name: 'Calvin Harris', genre: 'electronic', priority: true },
  { name: 'Avicii', genre: 'electronic', priority: true },
  { name: 'Skrillex', genre: 'electronic' },
  { name: 'Martin Garrix', genre: 'electronic' },
  { name: 'Marshmello', genre: 'electronic' },
  { name: 'Zedd', genre: 'electronic' },
  { name: 'David Guetta', genre: 'electronic' },
  { name: 'Deadmau5', genre: 'electronic' },
  { name: 'The Chainsmokers', genre: 'electronic' },
  { name: 'Swedish House Mafia', genre: 'electronic' },
  { name: 'Alan Walker', genre: 'electronic' },
  { name: 'DJ Snake', genre: 'electronic' },
  { name: 'Tiësto', genre: 'electronic' },
  { name: 'Kygo', genre: 'electronic' },
  { name: 'Disclosure', genre: 'electronic' },
  { name: 'Fred again..', genre: 'electronic' },
  { name: 'Flume', genre: 'electronic' },
  { name: 'Odesza', genre: 'electronic' },
  { name: 'RÜFÜS DU SOL', genre: 'electronic' },
  { name: 'Kaskade', genre: 'electronic' },
  { name: 'Armin van Buuren', genre: 'electronic' },
  { name: 'Major Lazer', genre: 'electronic' },
  { name: 'Diplo', genre: 'electronic' },
  { name: 'Galantis', genre: 'electronic' },
  { name: 'Robin Schulz', genre: 'electronic' },
  { name: 'Lost Frequencies', genre: 'electronic' },
  { name: 'Illenium', genre: 'electronic' },
  { name: 'San Holo', genre: 'electronic' },
  { name: 'Gryffin', genre: 'electronic' },
  { name: 'Madeon', genre: 'electronic' },
  { name: 'Porter Robinson', genre: 'electronic' },
  { name: 'CHVRCHES', genre: 'electronic' },
  { name: 'M83', genre: 'electronic' },
  { name: 'The Prodigy', genre: 'electronic' },
  { name: 'The Chemical Brothers', genre: 'electronic' },
  { name: 'Fatboy Slim', genre: 'electronic' },
  { name: 'Aphex Twin', genre: 'electronic' },
  { name: 'Bonobo', genre: 'electronic' },
  { name: 'Four Tet', genre: 'electronic' },
  { name: 'Caribou', genre: 'electronic' },
  { name: 'Bicep', genre: 'electronic' },
  { name: 'Peggy Gou', genre: 'electronic' },
  { name: 'Fisher', genre: 'electronic' },
  { name: 'John Summit', genre: 'electronic' },
  { name: 'Dom Dolla', genre: 'electronic' },

  // ==========================================
  // 7. HEAVY METAL & HARD ROCK
  // ==========================================
  { name: 'Metallica', genre: 'metal', priority: true },
  { name: 'Iron Maiden', genre: 'metal', priority: true },
  { name: 'Black Sabbath', genre: 'metal', priority: true },
  { name: 'Judas Priest', genre: 'metal' },
  { name: 'Megadeth', genre: 'metal' },
  { name: 'Slayer', genre: 'metal' },
  { name: 'Pantera', genre: 'metal' },
  { name: 'Slipknot', genre: 'metal' },
  { name: 'System of a Down', genre: 'metal' },
  { name: 'Korn', genre: 'metal' },
  { name: 'Deftones', genre: 'metal' },
  { name: 'Rammstein', genre: 'metal' },
  { name: 'Avenged Sevenfold', genre: 'metal' },
  { name: 'Disturbed', genre: 'metal' },
  { name: 'Godsmack', genre: 'metal' },
  { name: 'Five Finger Death Punch', genre: 'metal' },
  { name: 'Bring Me The Horizon', genre: 'metal' },
  { name: 'Ghost', genre: 'metal' },
  { name: 'Mastodon', genre: 'metal' },
  { name: 'Gojira', genre: 'metal' },
  { name: 'Tool', genre: 'metal' },
  { name: 'A Perfect Circle', genre: 'metal' },
  { name: 'Lamb of God', genre: 'metal' },
  { name: 'Killswitch Engage', genre: 'metal' },
  { name: 'Bullet for My Valentine', genre: 'metal' },
  { name: 'Trivium', genre: 'metal' },
  { name: 'Opeth', genre: 'metal' },
  { name: 'Dream Theater', genre: 'metal' },
  { name: 'Nightwish', genre: 'metal' },
  { name: 'Motorhead', genre: 'metal' },
  { name: 'Ozzy Osbourne', genre: 'metal' },
  { name: 'Dio', genre: 'metal' },
  { name: 'Anthrax', genre: 'metal' },
  { name: 'Sepultura', genre: 'metal' },
  { name: 'In Flames', genre: 'metal' },
  { name: 'Arch Enemy', genre: 'metal' },
  { name: 'Bad Omens', genre: 'metal' },
  { name: 'Sleep Token', genre: 'metal' },
  { name: 'Architects', genre: 'metal' },
  { name: 'Spiritbox', genre: 'metal' },

  // ==========================================
  // 8. COUNTRY & AMERICANA
  // ==========================================
  { name: 'Johnny Cash', genre: 'country', priority: true },
  { name: 'Dolly Parton', genre: 'country', priority: true },
  { name: 'Willie Nelson', genre: 'country', priority: true },
  { name: 'Chris Stapleton', genre: 'country', priority: true },
  { name: 'Zach Bryan', genre: 'country', priority: true },
  { name: 'Morgan Wallen', genre: 'country' },
  { name: 'Luke Combs', genre: 'country' },
  { name: 'Kacey Musgraves', genre: 'country' },
  { name: 'Carrie Underwood', genre: 'country' },
  { name: 'Miranda Lambert', genre: 'country' },
  { name: 'Keith Urban', genre: 'country' },
  { name: 'Tim McGraw', genre: 'country' },
  { name: 'Kenny Chesney', genre: 'country' },
  { name: 'Garth Brooks', genre: 'country' },
  { name: 'George Strait', genre: 'country' },
  { name: 'Alan Jackson', genre: 'country' },
  { name: 'Shania Twain', genre: 'country' },
  { name: 'Faith Hill', genre: 'country' },
  { name: 'Brad Paisley', genre: 'country' },
  { name: 'Blake Shelton', genre: 'country' },
  { name: 'Eric Church', genre: 'country' },
  { name: 'Jason Aldean', genre: 'country' },
  { name: 'Kane Brown', genre: 'country' },
  { name: 'Thomas Rhett', genre: 'country' },
  { name: 'Maren Morris', genre: 'country' },
  { name: 'Kelsea Ballerini', genre: 'country' },
  { name: 'Tyler Childers', genre: 'country' },
  { name: 'Colter Wall', genre: 'country' },
  { name: 'Sturgill Simpson', genre: 'country' },
  { name: 'Jason Isbell', genre: 'country' },
  { name: 'Lainey Wilson', genre: 'country' },
  { name: 'Cody Johnson', genre: 'country' },
  { name: 'Bailey Zimmerman', genre: 'country' },
  { name: 'Jelly Roll', genre: 'country' },
  { name: 'Darius Rucker', genre: 'country' },
  { name: 'Lady A', genre: 'country' },
  { name: 'Little Big Town', genre: 'country' },
  { name: 'Rascal Flatts', genre: 'country' },
  { name: 'Zac Brown Band', genre: 'country' },
  { name: 'Brooks & Dunn', genre: 'country' },

  // ==========================================
  // 9. JAZZ & BLUES
  // ==========================================
  { name: 'Miles Davis', genre: 'jazz', priority: true },
  { name: 'Frank Sinatra', genre: 'jazz', priority: true },
  { name: 'Louis Armstrong', genre: 'jazz', priority: true },
  { name: 'Nina Simone', genre: 'jazz' },
  { name: 'Ella Fitzgerald', genre: 'jazz' },
  { name: 'Dave Brubeck', genre: 'jazz' },
  { name: 'Nat King Cole', genre: 'jazz' },
  { name: 'Thelonious Monk', genre: 'jazz' },
  { name: 'Dizzy Gillespie', genre: 'jazz' },
  { name: 'Billie Holiday', genre: 'jazz' },
  { name: 'John Coltrane', genre: 'jazz' },
  { name: 'Ray Charles', genre: 'jazz' },
  { name: 'B.B. King', genre: 'jazz' },
  { name: 'Duke Ellington', genre: 'jazz' },
  { name: 'Chet Baker', genre: 'jazz' },
  { name: 'Muddy Waters', genre: 'jazz' },
  { name: 'Howlin\' Wolf', genre: 'jazz' },
  { name: 'Stevie Ray Vaughan', genre: 'jazz' },
  { name: 'Eric Clapton', genre: 'jazz' },
  { name: 'Robert Johnson', genre: 'jazz' },
  { name: 'Buddy Guy', genre: 'jazz' },
  { name: 'Albert King', genre: 'jazz' },
  { name: 'Freddie King', genre: 'jazz' },
  { name: 'John Lee Hooker', genre: 'jazz' },
  { name: 'Etta James', genre: 'jazz' },
  { name: 'Gary Clark Jr.', genre: 'jazz' },
  { name: 'Joe Bonamassa', genre: 'jazz' },
  { name: 'Marcus Miller', genre: 'jazz' },
  { name: 'Herbie Hancock', genre: 'jazz' },
  { name: 'Chick Corea', genre: 'jazz' },
  { name: 'Wayne Shorter', genre: 'jazz' },
  { name: 'Bill Evans', genre: 'jazz' },
  { name: 'Stan Getz', genre: 'jazz' },
  { name: 'Wes Montgomery', genre: 'jazz' },
  { name: 'Charlie Parker', genre: 'jazz' },
  { name: 'Sarah Vaughan', genre: 'jazz' },
  { name: 'Dinah Washington', genre: 'jazz' },
  { name: 'Norah Jones', genre: 'jazz' },
  { name: 'Diana Krall', genre: 'jazz' },
  { name: 'Gregory Porter', genre: 'jazz' },
  { name: 'Kamasi Washington', genre: 'jazz' },
  { name: 'Robert Glasper', genre: 'jazz' },
  { name: 'Esperanza Spalding', genre: 'jazz' },
  { name: 'Snarky Puppy', genre: 'jazz' },

  // ==========================================
  // 10. CLASSICAL & INSTRUMENTAL
  // ==========================================
  { name: 'Ludwig van Beethoven', genre: 'classical', priority: true },
  { name: 'Wolfgang Amadeus Mozart', genre: 'classical', priority: true },
  { name: 'Johann Sebastian Bach', genre: 'classical', priority: true },
  { name: 'Frederic Chopin', genre: 'classical' },
  { name: 'Pyotr Ilyich Tchaikovsky', genre: 'classical' },
  { name: 'Claude Debussy', genre: 'classical' },
  { name: 'Antonio Vivaldi', genre: 'classical' },
  { name: 'Johannes Brahms', genre: 'classical' },
  { name: 'Franz Schubert', genre: 'classical' },
  { name: 'George Frideric Handel', genre: 'classical' },
  { name: 'Hans Zimmer', genre: 'classical' },
  { name: 'John Williams', genre: 'classical' },
  { name: 'Ludovico Einaudi', genre: 'classical' },
  { name: 'Max Richter', genre: 'classical' },
  { name: 'Yiruma', genre: 'classical' },
  { name: 'Ennio Morricone', genre: 'classical' },
  { name: 'Howard Shore', genre: 'classical' },
  { name: 'Thomas Newman', genre: 'classical' },
  { name: 'Ramin Djawadi', genre: 'classical' },
  { name: 'Yo-Yo Ma', genre: 'classical' },
  { name: 'Itzhak Perlman', genre: 'classical' },
  { name: 'Lang Lang', genre: 'classical' },
  { name: 'Glenn Gould', genre: 'classical' },
  { name: 'Andrea Bocelli', genre: 'classical' },
  { name: 'Luciano Pavarotti', genre: 'classical' },
  { name: 'London Symphony Orchestra', genre: 'classical' },
  { name: 'Berlin Philharmonic', genre: 'classical' },

  // ==========================================
  // 11. REGGAE & SKA
  // ==========================================
  { name: 'Bob Marley & The Wailers', genre: 'reggae', priority: true },
  { name: 'Peter Tosh', genre: 'reggae' },
  { name: 'Jimmy Cliff', genre: 'reggae' },
  { name: 'Toots & The Maytals', genre: 'reggae' },
  { name: 'Burning Spear', genre: 'reggae' },
  { name: 'Black Uhuru', genre: 'reggae' },
  { name: 'UB40', genre: 'reggae' },
  { name: 'Damian Marley', genre: 'reggae' },
  { name: 'Ziggy Marley', genre: 'reggae' },
  { name: 'Chronixx', genre: 'reggae' },
  { name: 'Protoje', genre: 'reggae' },
  { name: 'Koffee', genre: 'reggae' },
  { name: 'Shaggy', genre: 'reggae' },
  { name: 'Sean Paul', genre: 'reggae' },
  { name: 'Rebelution', genre: 'reggae' },
  { name: 'SOJA', genre: 'reggae' },
  { name: 'Stick Figure', genre: 'reggae' },
  { name: 'Iration', genre: 'reggae' },
  { name: 'The Green', genre: 'reggae' },
  { name: 'Sublime', genre: 'reggae' },
  { name: 'Slightly Stoopid', genre: 'reggae' },
  { name: 'The Skatalites', genre: 'reggae' },
  { name: 'Desmond Dekker', genre: 'reggae' },
  { name: 'Steel Pulse', genre: 'reggae' },
  { name: 'Gregory Isaacs', genre: 'reggae' },

  // ==========================================
  // 12. LATIN CROSSOVER (English catalog focus)
  // ==========================================
  { name: 'Shakira', genre: 'pop' },
  { name: 'Enrique Iglesias', genre: 'pop' },
  { name: 'Ricky Martin', genre: 'pop' },
  { name: 'Gloria Estefan', genre: 'pop' },
  { name: 'Marc Anthony', genre: 'pop' },
  { name: 'Jennifer Lopez', genre: 'pop' },
  { name: 'Pitbull', genre: 'hip-hop' },
  { name: 'Becky G', genre: 'pop' },
  { name: 'Selena Gomez', genre: 'pop' },
  { name: 'Kali Uchis', genre: 'r-and-b' },
];
